### ISSUE TITLE
Drug_Names are not being put on the report

### ISSUE THREAD

**Issue by jorgemlferreira** [CancerRxGene/gdsctools#140]
Hello. The objects contain all the information about the drug decode. However, when the report is generated, the drug htmls do not contain information either about the the drug name or the drug target. It was working in 0.11.3 but no longer works for 0.13. How can I solve this?

Best regards,

Jorge Ferreira

**Comment by cokelaer** [comment]
I have fixed this issue locally and will submit the fix asap with a couple of other small issues in the HTML reports. Thanks for reporting the pbl.

**Comment by cokelaer** [comment]
This works again in the latest version 0.13.1
