### ISSUE TITLE
Bug in folder creation when tissue type is unspecified in ANOVAReport( )

### ISSUE THREAD

**Issue by elisabeth-chen** [CancerRxGene/gdsctools#147]
Following section 12. Reproducibility on gdsctools.readthedocs, 

When calling::
`import wget #For python 3, wget is not default`
`wget.download(http://www.cancerrxgene.org/gdsc1000/Data/anova/BRCA/DATA/INPUT/ANOVA_input.txt)`
`from gdsctools import *`
`an = ANOVA("ANOVA_input.txt", "ANOVA_input.txt")`
`an.setttings.pvalue_correction_method = "qvalue"`
`an.settings.equal_var_ttest = False`
`report = ANOVAReport(an)`
`report.settings.directory = "BRCA"`
`report.create_html_pages()`

The manova is created when defining the ANOVAReport class and is created in folder "unspecified". Setting report.settings.directory = "BRCA" creates a new folder "BRCA", where the html report is saved. However, original manova.html is still located in "unspecified/associations/manova.html", so clicking on the "MANOVA Results" link in section 3 of the html index (Explore all signfiicant results), gives a missing file error.

**Comment by cokelaer** [comment]
This should work as expected now within the git source code
