### ISSUE TITLE
Error when loading these data frames

### ISSUE THREAD

**Issue by elisabeth-chen** [CancerRxGene/gdsctools#149]
Hi Thomas, 

The files attached have been generated through my script. Both the genomic_matrix and the ic50_matrix are well accepted by the IC50() and GenomicFeatures() readers. However, when I try to call the anova_all() or anova_one_drug_one_feature() functions, there are a string of errors.
It seems to be unable to use the drug IDs, even though they are present in the "ANOVA.drugIds" list.

[test_files.zip](https://github.com/CancerRxGene/gdsctools/files/339132/test_files.zip)

Thanks for having a look!

**Comment by cokelaer** [comment]
There are two issues. 

First wrt to the IC50s: a bug was introduced in the previous commit to convert the IC50 dataframe index into integer (using astype) without a proper cast of the float numbers into integer). This is now fixed.

The other issue comes from the genomic features. In your file, the "CELL_LINE" columns is not known and considered to be a feature. I have added a code to ignore that specific column. 

I could now read you test files and perform the analysis

**Comment by elisabeth-chen** [comment]
Hi Thomas, 

Thanks for fixing this!

I installed the new update. Now, when I use the same tables, 
`an = ANOVA( "./ic50_matrix.csv", ...) `
works, but this does not: 
`ic = IC50( "./ic50_matrix.csv" )`
`an = ANOVA( ic , .... )`

It gives me an error that "COSMIC_ID column could not be found in the header" for the IC50 readers functions.

**Comment by cokelaer** [comment]
Should be fixes now
