### ISSUE TITLE
Error while creating Association html

### ISSUE THREAD

**Issue by jorgemlferreira** [CancerRxGene/gdsctools#152]
Hello.

I'm using the most recent version of the GDSCtools and I'm getting an error which crashes the generation of the Association html pages. The 
[error.txt](https://github.com/CancerRxGene/gdsctools/files/425139/error.txt) contains the traceback of the error. Can you help me with this? My guess is that somehow the GDSCtools can't handle the fact that there is not enough information for the creation of the html page taking in account the MSI factor.

Best regards,

Jorge Ferreira

Edit1: in boxplot.py, i added the
if data is None:
    return ""

to the get_html_msi(self) method and it works now. It is supposed to be like this?

Best regards again,

Jorge Ferreira

**Comment by howard-lightfoot** [comment]
I have had similar problems. You can also work around it with:

gg.settings.include_MSI_factor = False

**Comment by cokelaer** [comment]
Hi Jorge, Howard,
A small test example would help me debugging/improving this unwanted behaviour. 
best
Thomas

**Comment by cokelaer** [comment]
The MSI factor must be included in the regression as shown in this page:

http://gdsctools.readthedocs.io/en/master/anova_parttwo.html#regression-analysis

In the new version (v0.16), as it will be explained soon in the doc, you may set your own formula for the regression using the settings.regression_formula attribute.

**Comment by cokelaer** [comment]
Hi Jorge, 
This should be fixed now in v0.16
