### ISSUE TITLE
Error while loading data for standalone application

### ISSUE THREAD

**Issue by cy-bao** [CancerRxGene/gdsctools#153]
Loading these data and running standalone application results in following error for me. I want to perform a ADAF analyze. Thanks!

My code: 
gdsctools_anova -I lnIC50.tsv -F gf.tsv -D DrugDecode.tsv

My files:
lnIC50.tsv
COSMIC_ID   547 548
22RV1_PRAD  0.71772164  0.59983449
2313287_STAD    -2.27012681 1.37700607
42MGBA_LGG  -2.50334478 2.21186582

gf.tsv
COSMIC_ID   TISSUE_FACTOR   mut1    mut2
201T_LUCA   LUCA    1   0
22RV1_PRAD  PRAD    1   0
2313287_STAD    STAD    1   0

DrugDecode.tsv
DRUG_ID DRUG_NAME   DRUG_TARGET
2   16-BETA-BROMOANDROSTERONE  
3   "1S,3R-RSL-3"   GPX4
4   3-CL-AHPC   NR0B2

ERROR:
# Welcome to GDSCTools standalone

/usr/local/lib/python2.7/site-packages/gdsctools/readers.py:635: UserWarning: column named 'MSI_FACTOR' not found
  warnings.warn("column named '%s' not found" % self.colnames.msi)
WARNING: 372 cosmic identifiers in your IC50 could not be found in the genomic feature matrix. They will be dropped. Consider using a user-defined genomic features matrix
TISSUE FACTOR : NOT included
MEDIA FACTOR : NOT included
MSI FACTOR : NOT included
FEATURE FACTOR : included
Traceback (most recent call last):
  File "/usr/local/bin/gdsctools_anova", line 9, in <module>
    load_entry_point('gdsctools==0.14.0', 'console_scripts', 'gdsctools_anova')()
  File "/usr/local/lib/python2.7/site-packages/gdsctools/pipelines.py", line 140, in anova_pipeline
    options.drug = int(options.drug)
TypeError: int() argument must be a string or a number, not 'NoneType'

PS: These files worked well in python shell (ADAF).

That also worked when I changed the code to:
gdsctools_anova -I lnIC50.tsv -F gf.tsv -D DrugDecode.tsv -d 321

That resulted in ODAF analyze. But, what I need is  ADAF analyze.  From the source code, I saw "options.drug = int(options.drug)" is a essential step. So, how can I perform ADAF analyze with my own data in standalone application. I will really appreciate your help!

Since I can find "int(options.drug)" in the function of ODOF and ODAF, is it reasonable to delete "options.drug = int(options.drug)"  in line 140 in pipelines.py?

**Comment by cokelaer** [comment]
Sorry for the long delay in the answer.
Not sure if this is the reason for the failure but for now drug identifiers must be integers. Maybe the version you used for not as strict as the newest version, which explain why it was working in the library and not in the standalone. The standalone checks that drug identifier as integer and now the library also does that check. Besides, I noticed in your input files, your cosmic ids are also not integers. This may not be convenient for your input data but this is for consistency with the name (identifier by definition is an integer is databases).

**Comment by cy-bao** [comment]
Thank you for the information!
