### ISSUE TITLE
Errors running ANOVA

### ISSUE THREAD

**Issue by carolinie36** [CancerRxGene/gdsctools#154]
ODOF, ODAF, and ADAF are all working on the sample data provided from the gdsctools, however, when I tried to input my data(Drug response and genomic feature), only ODOF works. After computing ODOF, other modes are still not worked. Here's the error message I've got. Oh, and I am currently using the recent version of GDSCtools.
## In [55]: result=ctrp.anova_one_drug(1059)

TypeError                                 Traceback (most recent call last)
<ipython-input-55-3419be4e0c3e> in <module>()
----> 1 result=ctrp.anova_one_drug(1059)

C:\Users\KM Hong\Anaconda2\lib\site-packages\gdsctools\anova.pyc in anova_one_drug(self, drug_id, animate, output)
    758             # Instead, we require dictionaries
    759             this = self.anova_one_drug_one_feature(drug_id, feature,
--> 760                     production=True)
    761             if this['ANOVA_FEATURE_pval'] is not None:
    762                 res[feature] = this

C:\Users\KM Hong\Anaconda2\lib\site-packages\gdsctools\anova.pyc in anova_one_drug_one_feature(self, drug_id, feature_name, show, production, directory)
    305         # This is now pretty fast accounting for 45 seconds
    306         # for 265 drugs and 988 features
--> 307         odof = self._get_one_drug_one_feature_data(drug_id, feature_name)
    308
    309         # if the status is False, it means the number of data points

C:\Users\KM Hong\Anaconda2\lib\site-packages\gdsctools\anova.pyc in _get_one_drug_one_feature_data(self, drug_id, feature_name, diagnostic_only)
    188         # compute length of pos/neg features and MSI
    189         dd.positive_feature = dd.masked_features.sum()
--> 190         dd.negative_feature = len(dd.masked_features) - dd.positive_feature
    191
    192         # Some validity tests to run the analysis or not

TypeError: unsupported operand type(s) for -: 'int' and 'str'

I am still trying to figure it out but the information from google is not that helpful.

**Comment by cokelaer** [comment]
Could you please provide a running test example with the input data you have used ?

**Comment by cokelaer** [comment]
There were a few updates in version 0.15.0, which may have solved your issue. If you still experience the issue, please send a test example.

**Comment by cokelaer** [comment]
Again, a few updates made in version 0.16.X that should make the analysis more robust. 

Some issues fixed  recently leading to this type of error message:
- integer used for drug identifiers were too large (should be less than 2^64 
- MSI column is not diverse (all ones or all zeros)

**Comment by cokelaer** [comment]
Closing since there was no feedback, I assume this was fixed. Can be reopen if needed
