### ISSUE TITLE
syntax for settings

### ISSUE THREAD

**Issue by dgcovell** [CancerRxGene/gdsctools#167]
Please provide the steps for modifying 'settings' for ANOVA. Efforts to use --settings fn.name in standalone and python.2.7 modifications as in help(ANOVA) where:

V17 ::
        gdsc.settings.pvalue_cortrection_method = 'qvalue'

do not work. gdsc = ANOVA(ic_v17,gf_v17) yields gdsc.settings that are different from specified. The default set overrides my specifications. In addition, there are no entries in the html_gdsc_anova directory for INPUT and OUTPUT.
 
Now that the X11forwaring issue is resolved, I am seeking to generate the web available volcano and scatter plots for erlotinib. An explicit sequence of steps to regenerate these web results for erlotinib would be most appreciated.

I would add that the 2016 article's reference to http://www.cancerrxgene.org/gdsc1000/Data/anova/PANCAN/DATA/HTML_elements/associations/a306.html is not available.

**Comment by cokelaer** [comment]
If I understand correctly your issues, you have several questions:


- So, for the settings, you seem to be correct indeed, the settings is not taken into account. I will open a new issue to specifically fix this. 
- As for the "no entries for INPUT/OUTPUT", I will need more information. A test example maybe ?

- as for the broken link : the link indeed changed and the doc may not be up-to-date. could you please indicate the page or documentation where you saw that typo ?

thanks

**Comment by cokelaer** [comment]
- point1: you may have a typo. You wrote "pvalue_cortrection_method ". In my case only the settings for the volcano was not working as mentionned in #168 but this is also fixed now
- point2 : we need more information such as real reproducible example. If you can open another issue specifically for this problem. thanks
- point3: corrected in the doc. updated on gdsctools.readthedocs.io
